{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Main where

import Data.Typeable (Proxy(..))
import Test.Hspec
import Test.Hspec.QuickCheck

import PropMime
import Instances ()

import Gitea.Model
import Gitea.MimeTypes

main :: IO ()
main =
  hspec $ modifyMaxSize (const 10) $ do
    describe "JSON instances" $ do
      pure ()
      propMimeEq MimeJSON (Proxy :: Proxy AccessToken)
      propMimeEq MimeJSON (Proxy :: Proxy AddCollaboratorOption)
      propMimeEq MimeJSON (Proxy :: Proxy AddTimeOption)
      propMimeEq MimeJSON (Proxy :: Proxy AnnotatedTag)
      propMimeEq MimeJSON (Proxy :: Proxy AnnotatedTagObject)
      propMimeEq MimeJSON (Proxy :: Proxy Attachment)
      propMimeEq MimeJSON (Proxy :: Proxy Branch)
      propMimeEq MimeJSON (Proxy :: Proxy Comment)
      propMimeEq MimeJSON (Proxy :: Proxy Commit)
      propMimeEq MimeJSON (Proxy :: Proxy CommitMeta)
      propMimeEq MimeJSON (Proxy :: Proxy CommitUser)
      propMimeEq MimeJSON (Proxy :: Proxy ContentsResponse)
      propMimeEq MimeJSON (Proxy :: Proxy CreateEmailOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateFileOptions)
      propMimeEq MimeJSON (Proxy :: Proxy CreateForkOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateGPGKeyOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateHookOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateIssueCommentOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateIssueOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateKeyOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateLabelOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateMilestoneOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateOrgOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreatePullRequestOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateReleaseOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateRepoOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateStatusOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateTeamOption)
      propMimeEq MimeJSON (Proxy :: Proxy CreateUserOption)
      propMimeEq MimeJSON (Proxy :: Proxy DeleteEmailOption)
      propMimeEq MimeJSON (Proxy :: Proxy DeleteFileOptions)
      propMimeEq MimeJSON (Proxy :: Proxy DeployKey)
      propMimeEq MimeJSON (Proxy :: Proxy EditAttachmentOptions)
      propMimeEq MimeJSON (Proxy :: Proxy EditDeadlineOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditGitHookOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditHookOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditIssueCommentOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditIssueOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditLabelOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditMilestoneOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditOrgOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditPullRequestOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditReleaseOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditRepoOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditTeamOption)
      propMimeEq MimeJSON (Proxy :: Proxy EditUserOption)
      propMimeEq MimeJSON (Proxy :: Proxy Email)
      propMimeEq MimeJSON (Proxy :: Proxy FileCommitResponse)
      propMimeEq MimeJSON (Proxy :: Proxy FileDeleteResponse)
      propMimeEq MimeJSON (Proxy :: Proxy FileLinksResponse)
      propMimeEq MimeJSON (Proxy :: Proxy FileResponse)
      propMimeEq MimeJSON (Proxy :: Proxy GPGKey)
      propMimeEq MimeJSON (Proxy :: Proxy GPGKeyEmail)
      propMimeEq MimeJSON (Proxy :: Proxy GitBlobResponse)
      propMimeEq MimeJSON (Proxy :: Proxy GitEntry)
      propMimeEq MimeJSON (Proxy :: Proxy GitHook)
      propMimeEq MimeJSON (Proxy :: Proxy GitObject)
      propMimeEq MimeJSON (Proxy :: Proxy GitTreeResponse)
      propMimeEq MimeJSON (Proxy :: Proxy Hook)
      propMimeEq MimeJSON (Proxy :: Proxy Identity)
      propMimeEq MimeJSON (Proxy :: Proxy InlineObject)
      propMimeEq MimeJSON (Proxy :: Proxy InlineResponse200)
      propMimeEq MimeJSON (Proxy :: Proxy Issue)
      propMimeEq MimeJSON (Proxy :: Proxy IssueDeadline)
      propMimeEq MimeJSON (Proxy :: Proxy IssueLabelsOption)
      propMimeEq MimeJSON (Proxy :: Proxy Label)
      propMimeEq MimeJSON (Proxy :: Proxy MarkdownOption)
      propMimeEq MimeJSON (Proxy :: Proxy MergePullRequestOption)
      propMimeEq MimeJSON (Proxy :: Proxy MigrateRepoForm)
      propMimeEq MimeJSON (Proxy :: Proxy Milestone)
      propMimeEq MimeJSON (Proxy :: Proxy Organization)
      propMimeEq MimeJSON (Proxy :: Proxy PRBranchInfo)
      propMimeEq MimeJSON (Proxy :: Proxy PayloadCommit)
      propMimeEq MimeJSON (Proxy :: Proxy PayloadCommitVerification)
      propMimeEq MimeJSON (Proxy :: Proxy PayloadUser)
      propMimeEq MimeJSON (Proxy :: Proxy Permission)
      propMimeEq MimeJSON (Proxy :: Proxy PublicKey)
      propMimeEq MimeJSON (Proxy :: Proxy PullRequest)
      propMimeEq MimeJSON (Proxy :: Proxy PullRequestMeta)
      propMimeEq MimeJSON (Proxy :: Proxy Reference)
      propMimeEq MimeJSON (Proxy :: Proxy Release)
      propMimeEq MimeJSON (Proxy :: Proxy RepoCommit)
      propMimeEq MimeJSON (Proxy :: Proxy Repository)
      propMimeEq MimeJSON (Proxy :: Proxy SearchResults)
      propMimeEq MimeJSON (Proxy :: Proxy ServerVersion)
      propMimeEq MimeJSON (Proxy :: Proxy Status)
      propMimeEq MimeJSON (Proxy :: Proxy Tag)
      propMimeEq MimeJSON (Proxy :: Proxy Team)
      propMimeEq MimeJSON (Proxy :: Proxy TrackedTime)
      propMimeEq MimeJSON (Proxy :: Proxy UpdateFileOptions)
      propMimeEq MimeJSON (Proxy :: Proxy User)
      propMimeEq MimeJSON (Proxy :: Proxy UserHeatmapData)
      propMimeEq MimeJSON (Proxy :: Proxy WatchInfo)
      
